### ISSUE TITLE
Publish new Pypi version

### ISSUE THREAD

**Issue by Amoki** [redzej/graphene-permissions#17]
Pypi version still has the bug fixed by https://github.com/redzej/graphene-permissions/commit/e22e2f32ed0e029513060db6f3e983cad0dd7b46
Can you publish a new version @redzej ?

**Comment by redzej** [comment]
@Amoki should be fixed right now, new version is 1.1.0 https://pypi.org/project/graphene-permissions/.
Sorry for the inconvenience.
